# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    listener.exception_listener:
        class: AppBundle\Listener\ExceptionListener
        arguments: ['@templating']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
